### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by brianveltman** [dkuk/timelog_on_issue_page#1]
I have installed it but seems nothing has been added nor changed.

**Comment by dkuk** [comment]
:) i dont remember. I'll get to server approx 9 of jan and answer.
Probably it generates hidden form on issue page which opens by button without page refresh. Also it can uses Hot buttons plugin (only for Redmine 2.0.3 and below)

**Comment by brianveltman** [comment]
Yea I hoped it would work without hot buttons since im running 2.2.0.
